# Generated by Django 3.0.5 on 2020-06-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='content',
            new_name='description',
        ),
    ]
