# Generated by Django 3.0.5 on 2020-07-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200701_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startedquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='startedquiz',
            name='student',
        ),
        migrations.AddField(
            model_name='assignedquiz',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='assignedquiz',
            name='status',
            field=models.CharField(choices=[('AS', 'Assigned'), ('SD', 'Started'), ('CO', 'Assigned')], default='AS', max_length=2),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answered', to='dashboard.Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selectedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_question', related_query_name='question', to='dashboard.Question'),
        ),
        migrations.DeleteModel(
            name='CompletedQuiz',
        ),
        migrations.DeleteModel(
            name='StartedQuiz',
        ),
    ]
