# Generated by Django 3.0.5 on 2020-07-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200701_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_question', to='dashboard.Question'),
        ),
    ]
